# Основные понятия Python

## Условные выражения (IF...ELSE, IF...ELIF)

Условные инструкции - это тип **структуры управления потоком**: блок кода, который может принимать решения, анализируя значения переменных. Условная инструкция представляет собой код, который может выполнять дополнительный код в зависимости от определенного условия.

### IF...ELSE
*Пример:* **Если** имеющаяся сумма больше стоимости книги, то вывести какая сумма останется после покупки, **иначе** вывести сообщение "Не хватает средств".

In [6]:
amount = int(input("Общая сумма:"))
price_book = int(input("Стоимость книги:"))

if amount >= price_book:
    amount-=price_book
    print("Остаток: {}".format(amount))
else:
    print("Недостаточно средств")

Общая сумма:1069
Стоимость книги:890
Остаток: 179


### IF...ELIF
*Пример:* **Если** имеющаяся сумма больше стоимости книги, то вывести какая сумма останется после покупки, **иначе если** не хватает только 100 рублей, то прибавить к имеющейся сумме 100 рублей и вывести сообщение "Книга куплена!", **иначе** вывести сообщение "Не хватает средств".

In [9]:
#Решение

amount = int(input("Общая сумма:"))
price_book = int(input("Стоимость книги:"))

if amount >= price_book:
    amount-=price_book
    print("Остаток: {}".format(amount))
elif (price_book - amount) <= 100:
    amount+=100
    print("Книга куплена!")
else:
    print("Недостаточно средств")

Общая сумма:1000
Стоимость книги:1500
Недостаточно средств


# Циклы

## FOR ... in ...

**for** - цикл, перебирающий итерируемый объект. Процесс перебора называется **итерированием**

In [36]:
#range(count) - 0,...,count

for item in range(20):
    print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [38]:
list_1 = [23, 12, 0, 45, 67, 100, 14]
 
for i in range(0, len(list_1), 2) :
    print(list_1[i])

23
0
67
14


In [84]:
string = "Hello,world!"
for char in string:
    print(char) #end='\n'

H
e
l
l
o
,
w
o
r
l
d
!


*Пример:* Вывести, сколько раз втречается каждый символ в строке.

In [100]:
#set(string)  #"abcdefabcrtyf".count('abc')
counted_chars = dict()
for char in set(string): 
    counted_chars.update({char: string.count(char)})
print(counted_chars)    

{'l': 3, 'o': 2, 'e': 1, 'r': 1, 'H': 1, 'w': 1, '!': 1, 'd': 1, ',': 1}


In [88]:
#Операции со строками

"+".join('5647389')  #"Hello, world, its me!".split(','), 'Hello\'+"World" ' 

'5+6+4+7+3+8+9'

## While


Цикл **while** выполняет код до тех пор, пока выражение истинно (принимает значение True)

`while выражение:
     код_для_выполнения`

In [109]:
x=10
while x>0:
    print('{}'.format(x))
    x-=1

10
9
8
7
6
5
4
3
2
1


In [111]:
x=10
while x>0:
    if x==5:
        print ("Цикл завершен")
        break
    else:
        print('{}'.format(x))
        x-=1

10
9
8
7
6
Цикл завершен


# Функции

**Функции** - составные инструкции, которые могут принимать данные ввода, выполнять указания и возвращать данные вывода. Функции позволяют определять и повторно использовать определенную функциональность.

In [125]:
def calculate_sum(x, y):  
    sum=x+y
    return sum

calculate_sum(10, 12)

22

In [40]:
#Область видимости

x=1
y=2
z=3

def f():
    print(x)
    print(y)
    print(z)
    
f()

1
2
3


In [43]:
def f():
    a=1
    b=2
    c=3
    #print(a)
    #print(b)
    #print(c)
    
print(a)

NameError: name 'a' is not defined

In [170]:
??calculate_sum

# NumPy

**NumPy** (от Numerical Python - "числовой Python") - библиотека, предназначенная для работы с числовыми массивами, как одномерными, так и многомерными. Массивы библиотеки NumPy похожи на встроенный тип данных Python list, но обеспечивает гораздо более эффективное хранение и операциис данными при росте размера массивов.


In [174]:
import numpy as np

In [133]:
arr_1 = np.array([2, 6, 3, 10, 16, 15, 23, 56])
arr_1

array([ 2,  6,  3, 10, 16, 15, 23, 56])

In [152]:
#первые элементы
arr_1[:3] 

array([2, 6, 3])

In [151]:
#с i последнего до n-j элемента

arr_1[1:-3]

array([ 6,  3, 10, 16])

In [153]:
#каждый второй элемент

arr_1[::2] 

array([ 2,  3, 16, 23])

In [154]:
#каждый второй элемент в обратном порядке, начиная с 5

arr_1[5::-2]

array([15, 10,  6])

In [17]:
arr_2 = np.array([range(i, i+3) for i in [2,4,6]])
arr_2

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [161]:
arr_2[1][2]

6

In [167]:
#все строки, каждый второй столбец

arr_2[:, ::2]

array([[2, 4],
       [4, 6],
       [6, 8]])

In [173]:
#объединение массивов
np.concatenate([arr_2, arr_2])   #np.concatenate([arr_2, arr_2], axis=1)

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8],
       [2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [19]:
np.sum(arr_2<7)

8

# Pandas
**Pandas** - библиотека на языке Python для обработки и анализа данных. Pandas является надстройкой над библиотекой NumPy, обеспечивающей эффективную реализацию класса DataFrame. Объекты **DataFrame** - многомерные массивы с метками для строк и столбцов, а также зачастую с неоднородным типом данных и/или пропущенными данными.

In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv('/Users/chekmarevaalfiya/Desktop/practice_IIS_451/iris.csv')
dataset

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [187]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [188]:
dataset.describe()

#Значение процентиля: сколько значений меньше заданного процентиля

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [186]:
dataset['petal.length'].dtypes  #'petal.width'

dtype('float64')

In [177]:
#обращение к элементу
dataset['petal.length'][3]

1.5

In [180]:
dataset['variety'].unique()

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [181]:
dataset[(dataset['variety']=='Setosa') | (dataset['variety']=='Versicolor')]

sepal.length  sepal.width  petal.length  petal.width     variety
0            5.1          3.5           1.4          0.2      Setosa
1            4.9          3.0           1.4          0.2      Setosa
2            4.7          3.2           1.3          0.2      Setosa
3            4.6          3.1           1.5          0.2      Setosa
4            5.0          3.6           1.4          0.2      Setosa
..           ...          ...           ...          ...         ...
95           5.7          3.0           4.2          1.2  Versicolor
96           5.7          2.9           4.2          1.3  Versicolor
97           6.2          2.9           4.3          1.3  Versicolor
98           5.1          2.5           3.0          1.1  Versicolor
99           5.7          2.8           4.1          1.3  Versicolor

[100 rows x 5 columns]

## Индексаторы: loc, iloc

- **loc** позволяет выполнить индексацию и срезы с использованием явного индекса
- **iloc** дает возможность выполнить индексацию и срезы, пременяя неявный индекс

In [7]:
data = pd.Series(['a', 'b', 'c', 'd'], index=[1, 3, 5, 7])
data

1    a
3    b
5    c
7    d
dtype: object

In [198]:
l=[0, 1, 2, 3]
l[1]

1

In [202]:
data[3]

'b'

In [13]:
data[1:3], data.loc[1:5]

(3    b
 5    c
 dtype: object,
 1    a
 3    b
 5    c
 dtype: object)

In [10]:
data.iloc[1:4]

3    b
5    c
7    d
dtype: object

## Группировка

In [38]:
dataset.groupby('variety').mean()

sepal.length  sepal.width  petal.length  petal.width
variety                                                         
Setosa             5.006        3.428         1.462        0.246
Versicolor         5.936        2.770         4.260        1.326
Virginica          6.588        2.974         5.552        2.026

In [29]:
dataset_group = dataset.groupby('variety').agg({
    'sepal.length': 'max',
    'sepal.width': 'min',
    'petal.length': 'mean',
    "petal.width": "last"
})
dataset_group

sepal.length  sepal.width  petal.length  petal.width
variety                                                         
Setosa               5.8          2.3         1.462          0.2
Versicolor           7.0          2.0         4.260          1.3
Virginica            7.9          2.2         5.552          1.8

In [28]:
dataset.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149])

In [30]:
dataset_group.index.values

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [35]:
dataset_group.reset_index('variety')

variety  sepal.length  sepal.width  petal.length  petal.width
0      Setosa           5.8          2.3         1.462          0.2
1  Versicolor           7.0          2.0         4.260          1.3
2   Virginica           7.9          2.2         5.552          1.8

In [36]:
dataset['new_column'] = 'Beauty'
dataset

sepal.length  sepal.width  petal.length  petal.width    variety  \
0             5.1          3.5           1.4          0.2     Setosa   
1             4.9          3.0           1.4          0.2     Setosa   
2             4.7          3.2           1.3          0.2     Setosa   
3             4.6          3.1           1.5          0.2     Setosa   
4             5.0          3.6           1.4          0.2     Setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  Virginica   
146           6.3          2.5           5.0          1.9  Virginica   
147           6.5          3.0           5.2          2.0  Virginica   
148           6.2          3.4           5.4          2.3  Virginica   
149           5.9          3.0           5.1          1.8  Virginica   

    new_column  
0       Beauty  
1       Beauty  
2       Beauty  
3       Beauty  
4       Beauty  
..         ...  
145     Beauty  
146     Beauty  
147     Beauty  
148     Beauty  
149     Beauty  

[150 rows x 6 columns]